controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
#---------- TP1 ----------#

premiertest:
    path: /premiertest
    controller: App\Controller\TestController::accueil
test:
    path: /test/{departement}
    controller: App\Controller\TestController::test
    defaults:
        departement: 0
    requirements:
        departement: \d+

#---------- TP2 ----------#

hello:
    path: /hello/{prenom}/{department}
    controller: App\Controller\HelloController::hello
    defaults:
        prenom: Personne
        department: 0
    requirements:
        department: \d+
hello2:
    path: /hello2/{prenom}
    controller: App\Controller\HelloController::hello2
    defaults:
        prenom: Personne
accueiltest:
    path: /accueiltest/{prenom}
    controller: App\Controller\Test2Controller::accueiltest
    defaults:
        prenom: Personne

#---------- Projet ----------#

accueil:
    path: /
    controller: App\Controller\AccueilController::accueil
homepage:
    path: /homepage
    controller: App\Controller\AccueilController::accueil

#---------- Gestion des biens et des catégories ----------#

addbien:
    path: /agence/bien/add
    controller: App\Controller\BienController::addbien
addcategorie:
    path: /agence/categorie/add
    controller: App\Controller\CategorieController::addcategorie

modifbien:
    path: /agence/bien/modif/
    controller: App\Controller\BienController::modifbien
    defaults:
        id: 0
    requirements:
        id: \d+
modifcategorie:
    path: /agence/categorie/modif
    controller: App\Controller\CategorieController::modifcategorie
    defaults:
        id: 0
    requirements:
        id: \d+

supprbien:
    path: /agence/bien/suppr
    controller: App\Controller\BienController::supprbien
supprbienfini:
    path: /agence/bien/suppr/fini
    controller: App\Controller\BienController::supprbienfini

supprcategorie:
    path: /agence/categorie/suppr
    controller: App\Controller\CategorieController::supprcategorie
        
supprcategoriefini:
    path: /agence/categorie/suppr/fini
    controller: App\Controller\CategorieController::supprcategoriefini
    
#---------- Logins ----------#

login_user:
    path: /login_user
    controller: App\Controller\LoginController::login_user
inscription_user:
    path: /inscription_user
    controller: App\Controller\LoginController::inscription_user
contact:
    path: /contact
    controller: App\Controller\AccueilController::contact

#---------- Biens ----------#

bien:
    path: /bien/{id}
    controller: App\Controller\BienController::bien
    defaults:
        id: 0
    requirements:
        id: \d+

#---------- Catégories ----------#

categorie:
    path: /categorie/{id}
    controller: App\Controller\CategorieControllerTypes::categorie
    defaults:
        id: 0
    requirements:
        id: \d+

#---------- Admin ----------#

admin:
    path: /admin
    controller: App\Controller\AdminController::admin
stats:
    path: /stats
    controller: App\Controller\AdminController::stats