controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
#---------- TP1 ----------#

premiertest:
    path: /premiertest
    controller: App\Controller\TestController::accueil
test:
    path: /test/{departement}
    controller: App\Controller\TestController::test
    defaults:
        departement: 0
    requirements:
        departement: \d+

#---------- TP2 ----------#

hello:
    path: /hello/{prenom}/{department}
    controller: App\Controller\HelloController::hello
    defaults:
        prenom: Personne
        department: 0
    requirements:
        department: \d+
hello2:
    path: /hello2/{prenom}
    controller: App\Controller\HelloController::hello2
    defaults:
        prenom: Personne
accueiltest:
    path: /accueiltest/{prenom}
    controller: App\Controller\Test2Controller::accueiltest
    defaults:
        prenom: Personne

#---------- Projet ----------#

accueil:
    path: /
    controller: App\Controller\AccueilController::accueil
homepage:
    path: /homepage
    controller: App\Controller\AccueilController::accueil

#---------- Gestion des biens et des catégories ----------#

addbien:
    path: /agence/bien/add
    controller: App\Controller\BienController::addbien
addcategorie:
    path: /agence/categorie/add
    controller: App\Controller\CategorieController::addcategorie

modifbien:
    path: /agence/bien/modif/{id}
    controller: App\Controller\BienController::modifbien
    defaults:
        id: 0
modifcategorie:
    path: /agence/categorie/modif/{id}
    controller: App\Controller\CategorieController::modifcategorie
    defaults:
        id: 0
supprbien:
    path: /agence/bien/suppr/{id}
    controller: App\Controller\BienController::supprbien
    defaults:
        id: 0
supprcategorie:
    path: /agence/categorie/suppr/{id}
    controller: App\Controller\CategorieController::supprcategorie
    defaults:
        id: 0

#---------- Logins ----------#

login_user:
    path: /login_user
    controller: App\Controller\LoginController::login_user
inscription_user:
    path: /inscription_user
    controller: App\Controller\LoginController::inscription_user
contact:
    path: /contact
    controller: App\Controller\AccueilController::contact

#---------- Biens ----------#

bien:
    path: /bien/{id}
    controller: App\Controller\BienController::bien
    defaults:
        id: 0

#---------- Catégories ----------#

categorie:
    path: /categorie/{id}
    controller: App\Controller\CategorieControllerTypes::categorie
    defaults:
        id: 0
