controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
#TP1
index:
    path: /premiertest
    controller: App\Controller\TestController::accueil
test:
    path: /test/{departement}
    controller: App\Controller\TestController::test
    defaults:
        departement: 0
    requirements:
        departement: \d+

#TP2
hello:
    path: /hello/{prenom}/{department}
    controller: App\Controller\HelloController::hello
    defaults:
        prenom: Personne
        department: 0
    requirements:
        department: \d+
hello2:
    path: /hello2/{prenom}
    controller: App\Controller\HelloController2::hello2

#Projet
accueil:
    path: /
    controller: App\Controller\AccueilController::accueil
homepage:
    path: /homepage
    controller: App\Controller\HomeController::index
