controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
index:
    path: /
    controller: App\Controller\TestController::index
test:
    path: /test/{departement}
    controller: App\Controller\TestController::test
    defaults:
        departement: 0
    requirements:
        departement: \d+
